language: python
sudo: false
script: true
notifications:
  email: false
before_deploy: ci/build.sh
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file: seer-pi-*.deb
  on:
    tags: true
    repo: skateman/seer-pi
